### ISSUE TITLE
MultiLogRecordProcessor log message

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [Vunovati/pino-opentelemetry-transport#106]
Was this line left in intentionally?

https://github.com/Vunovati/pino-opentelemetry-transport/blob/31acee463f1f9f5b720d539e003cf0dd029c935b/multi-log-processor.js#L15

It's adding an undesirable log to my application startup

**Comment by Vunovati** [comment]
This is not intentional. Fixed it. I will release it later today.
