### ISSUE TITLE
the "dilemma" over severity number map

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [Vunovati/pino-opentelemetry-transport#150]
Been thinking more about [this](https://github.com/Vunovati/pino-opentelemetry-transport/pull/146#discussion_r1515748872):

> I had a dilemma about whether to keep it or not. The potential downside would be that we would not detect if there are any changes in the @opentelemetry API. OTOH, this is unlikely to change soon.

The idea with the removal was to not have direct dependencies on the @opentelemetry packages particularly because of the frequent releases required of otlp-logger.

I've thought about a couple ways to guard against changes. 

### Option 1

Option 1 would be to keep the map how it is, export it and add a test like below. This is a little less future safe than option 2 but I think satisfies the concern while also not introducing any additional complexity to the library

```js
test('default severity number map', async ({ match }) => {
  const pinoLogLevels = pino.levels.values
  match(DEFAULT_SEVERITY_NUMBER_MAP, {
    [pino.levels.values.trace]: SeverityNumber.TRACE,
    [pino.levels.values.debug]: SeverityNumber.DEBUG,
    [pino.levels.values.info]: SeverityNumber.INFO,
    [pino.levels.values.warn]: SeverityNumber.WARN,
    [pino.levels.values.error]: SeverityNumber.ERROR,
    [pino.levels.values.fatal]: SeverityNumber.FATAL
  })
})
```

### Option 2

Option 2 is to add pino and @opentelemetry/api-logs as _peerDependencies_ with _loose_ definitions, and use them to create the map.

```json
  "peerDependencies": {
    "@opentelemetry/api-logs": ">=0.35.0", // This is when SeverityNumber was added
    "pino": "^8.0.0"
  },
```

```js
const DEFAULT_SEVERITY_NUMBER_MAP = {
  [pino.levels.values.trace]: SeverityNumber.TRACE,
  [pino.levels.values.debug]: SeverityNumber.DEBUG,
  [pino.levels.values.info]: SeverityNumber.INFO,
  [pino.levels.values.warn]: SeverityNumber.WARN,
  [pino.levels.values.error]: SeverityNumber.ERROR,
  [pino.levels.values.fatal]: SeverityNumber.FATAL
}
```

With this option, `SEVERITY_NAME_MAP` could be replaced with

```js
const SEVERITY_NAME_MAP = Object.fromEntries(Object.entries(SeverityNumber).map(([text, number]) => [number, text]));
```

### Option 3

<details>
<summary> this option is not good</summary>
Option 3 add @opentelemetry/api-logs as a _peerDependency_ with a _loose_ definition, and use the log level name to derive the severity number by passing logger itself or `logger.levels` to `toOpenTelemetry`

```js
const severityNumber =
    severityNumberMap[sourceObject.level] ?? SeverityNumber[logger.levels.labels[logEntry.level].toUpperCase()] ?? 0
```

This would have the added benefit of being able to create custom log levels in pino that require no additional configuration in pino-opentelemetry-transport to function if the level name matches an otel log severity. The `SEVERITY_NAME_MAP` could similarly be replaced as in option 2.

However, this would be breaking for anyone using custom level names but not level numbers, so its probably too "clever" for its own good
</details>

lmk your thoughts. happy to open a PR (not for 3 though). Option 1 is my preference personally.

**Comment by Vunovati** [comment]
I like option 1, too, because it gives us confidence during test runs and development. At the same time, we depend on `@opentelemetry/api-logs` only as a dev dependency, which is consistent with our approach so far (dev deps: @opentelemetry/sdk-node, @opentelemetry/sdk-node, etc.).
