### ISSUE TITLE
Contributing to Opentelemetry

### ISSUE THREAD

**Issue by mhennoch** [Vunovati/pino-opentelemetry-transport#158]
Hi! 

Just wondering if you have any plans on contributing this to [OTEL](https://github.com/open-telemetry/opentelemetry-js-contrib)? Winston and Bunyan recently got logs support. Pino the only one left.

**Comment by Vunovati** [comment]
Let me think about what steps would be necessary to achieve this. In general, I agree that having this repo in a prominent organization would be a good thing.

**Comment by mhennoch** [comment]
Been looking into adding a Pino transport to OTEL also. Created an issue [here](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2110). Let's continue the discussion there.
