### ISSUE TITLE
Allow ConsoleLogRecordExporter in development

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [Vunovati/pino-opentelemetry-transport#20]
When `NODE_ENV` is development I prefer to use `ConsoleLogRecordExporter` in addition to `OTLPLogExporter`. Would you be open to a PR that would allow folx to add additional exporters? This could be a new array option like `logRecordExporters` which would override the default exporter. A simpler option would be to swap lines [23 and 24](https://github.com/Vunovati/pino-opentelemetry-transport/blob/main/pino-opentelemetry-transport.js#L23-L24) in `pino-open-telemetry-transport.js` like so:

```js
  const logger = getOtlpLogger({
    logRecordExporter: new OTLPLogExporter()
    ...opts,
  })
```

But this wouldn't allow users to use both exporters.

I tried the below but `logs.getGlobalLoggerProvider()` just returned a `NoopLoggerProvider` which threw an error when adding the exporter.

```js
if (process.env.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT && process.env.NODE_ENV === 'development') {
  const loggerProvider = logs.getLoggerProvider();
  loggerProvider.addLogRecordProcessor(
    new SimpleLogRecordProcessor(new ConsoleLogRecordExporter())
  );
}
```

Are you open to a PR for either of these options?

**Comment by 10xLaCroixDrinker** [comment]
Relates to, possibly duplicates #3

**Comment by Vunovati** [comment]
Hello @10xLaCroixDrinker, This is definitely related to #3, which should address the concern of designing a good API that enables this and any other combination of exporters.

I think the first would be a more conservative option, so I'd be open to that PR.

Keep in mind that this is not an ideal or final API. It is possible that this option will not be supported in the long term. I'll also plan that the solution to #3 addresses your use case.

Cheers, looking forward to your PR ✌🏻

**Comment by Vunovati** [comment]
@10xLaCroixDrinker, the API has been updated (not published yet). The use case for Console log is still supported but with a different API. I believe this example is similar to your use case: https://github.com/Vunovati/pino-opentelemetry-transport/tree/main/examples/using-multiple-record-processors
