### ISSUE TITLE
Make it possible to select multiple combinations of processors and exporters

### ISSUE THREAD

**Issue by Vunovati** [Vunovati/pino-opentelemetry-transport#3]
I couldn't think of a simple API that would support various combinations of exporters (GRPC, HTTP, Console, InMemory ...) and processors(Batch, simple ...). Do you have some suggestions? 

_Originally posted by @Vunovati in https://github.com/Vunovati/pino-opentelemetry-transport/pull/1#discussion_r1273448920_

**Comment by mcollina** [comment]
A few things:

1. provide a way to create your pino transport for OTLP based on this one
2. add support for the more basic cases via options, I would recommend adding HTTP support as it seems more popular
