### ISSUE TITLE
Error: pino-opentelemetry-transport tried to access @opentelemetry/resources, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by Jalkar** [Vunovati/pino-opentelemetry-transport#39]
I believe it misses a lines in package.json
https://classic.yarnpkg.com/lang/en/docs/pnp/troubleshooting/

**Comment by Vunovati** [comment]
Give it another shot. I just released the fix in 0.3.0

**Comment by Jalkar** [comment]
Solved for "resources", but the error is on the next package :)
Error: @opentelemetry/sdk-logs tried to access @opentelemetry/api (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

**Comment by Vunovati** [comment]
@Jalkar

Can you please provide a way to reproduce this? What does your package.json
look like?

Thanks

**Comment by Jalkar** [comment]
I manage to bypass my error by declaring some "packageExtensions" in my yarnrc.yml.

  'pino-opentelemetry-transport@*':
    dependencies:
      '@opentelemetry/sdk-logs': '*'
      '@opentelemetry/api': '*'

this allow to declare that the following installed package can be used as a depandancy to your package
