### ISSUE TITLE
Add support for `InMemoryLogRecordExporter`

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [Vunovati/pino-opentelemetry-transport#95]
I have a testing use case where I'd like to use the `InMemoryLogRecordExporter` to validate the logs being produced. There is a slight incompatibility with the existing structure and this capability though. We cannot add it as simply as the others i.e.

```js
  if (exporterProtocol === 'memory') {
    return new InMemoryLogRecordExporter()
  }
```

That's because the tests need access to `exporter.getFinishedLogRecords()` and `exporter.reset()`. The clearest way I see to support this is to allow the user to pass the exporter directly in the options. I'd be happy to open such a PR but would you be open to it?

**Comment by Vunovati** [comment]
Hello @10xLaCroixDrinker, 

The approach you suggested may not work.

The way Pino works (from v7) is that it sends the serialised logs to a [worker_thread](https://nodejs.org/api/worker_threads.html#worker-threads) where the transports (such as pino-opentelemety-transport) are receiving it, deserialising it and doing their transporting but in different memory space. ([docs](https://github.com/pinojs/pino/blob/master/docs/transports.md#v7-transports)). We can only send types of data that are supported by the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#javascript_types).

Consequently, reaching into the transport's memory space from the main thread that instantiated Pino and ran your tests is impossible.


In the tests for this module, we've used two approaches:

1.  We've tested the translation and usage of OTEL SDK with InMemoryLogRecordExporter in [otlp-logger.test.js](https://github.com/Vunovati/pino-opentelemetry-transport/blob/1949033bd4da5b036ceda0020898692b3a30f67d/test/otlp-logger.test.js#L1-L120) but all of that happened without Pino. 

2. When we included Pino in our integration tests, we had to test by actually [looking](https://github.com/Vunovati/pino-opentelemetry-transport/blob/1949033bd4da5b036ceda0020898692b3a30f67d/test/pino-opentelemetry-transport.test.js#L187-L191) into the [opentelemetry collector instance](https://github.com/Vunovati/pino-opentelemetry-transport/blob/1949033bd4da5b036ceda0020898692b3a30f67d/test/pino-opentelemetry-transport.test.js#L16-L42) and see what logs it emits. 

The second option is the only way to test your use case. If you find a more elegant way to do it, please feel free to ping.


I hope this makes sense to you.

**Comment by Vunovati** [comment]
@10xLaCroixDrinker I'll close this if there is nothing left to add. Is that ok?

**Comment by 10xLaCroixDrinker** [comment]
Yeah, nothing left. I did end up just adding a collector in my integration test suite

**Comment by Vunovati** [comment]
Great. I am glad it worked out for you 👍
